format:
  revealjs:
    theme: [default, custom-dark.scss]  # Change to custom-dark.scss
    slide-number: true
    width: 1600
    height: 900
    margin: 0.1
    logo: "logo.png"  # Add your logo file
    footer: "Your Company Name"
    highlight-style: github
    code-font-family: "JetBrains Mono"
    code-overflow: wrap
    
execute:
  echo: true

